function style = set_style()
cmap = lines(7);
style.M.color = cmap(1, :);
style.E.color = cmap(2, :);
style.D10.color = cmap(3, :);
style.D1.color = cmap(5, :);
style.D1xwh.color = cmap(4, :);
for ff = string(fieldnames(style)')
    style.(ff).displayname = ff; 
end

set(groot, ...
	'defaultLineLineWidth', 3, ...
	'defaultAxesLineWidth', 2, ...
	'defaultAxesFontSize', 9, ...
	'defaultAxesFontWeight', 'bold', ...
	'defaultAxesFontName', 'nimbus sans', ...
	'defaultFigureUnits', 'inches', ...
    'defaultFigurePosition', [6.0972    5.2361    7.7778    5.8333], ...
	'defaultAxesOuterPosition', [0 0 1 1])
end
